# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
stages:
  - lint
  - test

default:
  interruptible: true  

variables:
  # tell Python-based tools to force color output
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

.cache_variables: &cache_variables
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

.before_script_template: &before_script
  # Ansible refuses to read from a world-writeable folder
  - chmod 0750 $CI_PROJECT_DIR
  - pip install -U pip
  - pip install --ignore-installed pipenv
  - pipenv install --dev

include:
  - project: hifis/templates/gitlab-ci
    file: /templates/reuse-compliance.yml

validate:
  stage: lint
  image: python:3.8
  variables: *cache_variables
  before_script:
    - *before_script
  script:
    - pipenv run molecule lint
  cache:
    key: pipenv
    paths:
      - .pipenv

test-ubuntu20.04:
  variables:
    MOLECULE_DISTRO: ubuntu:20.04
  extends: .moleculetest

test-centos8:
  variables:
    MOLECULE_DISTRO: centos:8
  extends: .moleculetest

.moleculetest:
  stage: test
  image: docker:latest
  variables: *cache_variables
  services:
    - docker:dind
  before_script:
    - apk update && apk add --no-cache
      python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh
    - docker info
    - python3 --version
    - *before_script
  script:
    - pipenv run molecule test
  cache:
    key: pipenv-alpine
    paths:
      - .pipenv

...
