# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: GitLab has been installed or upgraded
  become: yes
  set_fact:
    gitlab_is_upgraded: "{{ gitlab_install_output is defined and gitlab_install_output.changed }}"

...
