# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Converge
  hosts: all
  tasks:
    - name: "Include gitlab-base-role"
      include_role:
        name: "gitlab-base-role"
